// File generated by FlutterFire CLI.
// ignore_for_file: type=lint, lines_longer_than_80_chars, avoid_classes_with_only_static_members

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Firebase options for hostera24-f8585 (FlutterFire).
class DefaultFirebaseOptions {
  static const String _placeholder = 'REPLACE_ME_RUN_FLUTTERFIRE_CONFIGURE';

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError('Web nu este configurat.');
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions nu suportă $defaultTargetPlatform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAG4rdFpY-D-OOuKyUdnERYoHefOHC-h0w',
    appId: '1:757392952680:android:51bfff801c79b9fd3b5add',
    messagingSenderId: '757392952680',
    projectId: 'hostera24-f8585',
    storageBucket: 'hostera24-f8585.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBL8-xjW57Xi6uEIsA5yLGV3KE0M8CXRmY',
    appId: '1:757392952680:ios:2f97930640fd1fcf3b5add',
    messagingSenderId: '757392952680',
    projectId: 'hostera24-f8585',
    storageBucket: 'hostera24-f8585.firebasestorage.app',
    iosClientId: '757392952680-qhrurmtarfmsohj6udjt72mbjen5kcoc.apps.googleusercontent.com',
    iosBundleId: 'com.hostera24.hostera24',
  );

  static bool get isPlaceholder =>
      android.apiKey == _placeholder || android.appId == _placeholder;
}