-- UN SINGUR statement (fara WITH RECURSIVE, MySQL 5.7+).
-- Ruleaza DUPA seed-georgelutaoff-coduri.sql

INSERT INTO scanari (cod_qr_id, scanat_la)
SELECT c.id, NOW() - INTERVAL (d.n * 24 + h.oh) HOUR
FROM coduri_qr c
INNER JOIN firme f ON f.id = c.firma_id AND f.email = 'georgelutaoff@gmail.com'
CROSS JOIN (
  SELECT 0 AS n UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4
  UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9
  UNION ALL SELECT 10 UNION ALL SELECT 11 UNION ALL SELECT 12 UNION ALL SELECT 13 UNION ALL SELECT 14
  UNION ALL SELECT 15 UNION ALL SELECT 16 UNION ALL SELECT 17 UNION ALL SELECT 18 UNION ALL SELECT 19
  UNION ALL SELECT 20 UNION ALL SELECT 21 UNION ALL SELECT 22 UNION ALL SELECT 23 UNION ALL SELECT 24
  UNION ALL SELECT 25 UNION ALL SELECT 26 UNION ALL SELECT 27
) d
CROSS JOIN (
  SELECT 2 AS oh UNION ALL SELECT 9 UNION ALL SELECT 14 UNION ALL SELECT 19
) h
WHERE c.cod = 'GEORGE-INSTA-2026'
UNION ALL
SELECT c.id, NOW() - INTERVAL (d.n * 24 + 12) HOUR
FROM coduri_qr c
INNER JOIN firme f ON f.id = c.firma_id AND f.email = 'georgelutaoff@gmail.com'
CROSS JOIN (
  SELECT 0 AS n UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4
  UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9
  UNION ALL SELECT 10 UNION ALL SELECT 11 UNION ALL SELECT 12 UNION ALL SELECT 13 UNION ALL SELECT 14
  UNION ALL SELECT 15 UNION ALL SELECT 16 UNION ALL SELECT 17 UNION ALL SELECT 18 UNION ALL SELECT 19
  UNION ALL SELECT 20
) d
WHERE c.cod = 'GEORGE-INSTA-2026'
UNION ALL
SELECT c.id, NOW() - INTERVAL (wd.n * 24 + 17) HOUR
FROM coduri_qr c
INNER JOIN firme f ON f.id = c.firma_id AND f.email = 'georgelutaoff@gmail.com'
CROSS JOIN (
  SELECT 6 AS n UNION ALL SELECT 13 UNION ALL SELECT 20 UNION ALL SELECT 27
) wd
WHERE c.cod = 'GEORGE-INSTA-2026'
UNION ALL
SELECT c.id, NOW() - INTERVAL (d.n * 24 + h.oh) HOUR
FROM coduri_qr c
INNER JOIN firme f ON f.id = c.firma_id AND f.email = 'georgelutaoff@gmail.com'
CROSS JOIN (
  SELECT 0 AS n UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4
  UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9
  UNION ALL SELECT 10 UNION ALL SELECT 11 UNION ALL SELECT 12 UNION ALL SELECT 13
) d
CROSS JOIN (
  SELECT 6 AS oh UNION ALL SELECT 11 UNION ALL SELECT 16
) h
WHERE c.cod = 'GEORGE-TIKTOK-2026'
UNION ALL
SELECT c.id, NOW() - INTERVAL (d.n * 24 + h.oh) HOUR
FROM coduri_qr c
INNER JOIN firme f ON f.id = c.firma_id AND f.email = 'georgelutaoff@gmail.com'
CROSS JOIN (
  SELECT 0 AS n UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4
  UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9
) d
CROSS JOIN (
  SELECT 10 AS oh UNION ALL SELECT 18
) h
WHERE c.cod = 'GEORGE-GOOGLE-2026';
