-- +20 scanari pentru GEORGE-INSTA-2026 (georgelutaoff@gmail.com)
-- UN singur statement. DBeaver: Ctrl+A, Ctrl+Enter.

INSERT INTO scanari (cod_qr_id, scanat_la)
SELECT c.id, NOW() - INTERVAL (n.n * 6 + 1) HOUR
FROM coduri_qr c
INNER JOIN firme f ON f.id = c.firma_id AND f.email = 'georgelutaoff@gmail.com'
CROSS JOIN (
  SELECT 0 AS n UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4
  UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9
  UNION ALL SELECT 10 UNION ALL SELECT 11 UNION ALL SELECT 12 UNION ALL SELECT 13 UNION ALL SELECT 14
  UNION ALL SELECT 15 UNION ALL SELECT 16 UNION ALL SELECT 17 UNION ALL SELECT 18 UNION ALL SELECT 19
) n
WHERE c.cod = 'GEORGE-INSTA-2026';
